apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
    service: httpbin
spec:
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app: pomerium-httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pomerium-httpbin
  template:
    metadata:
      labels:
        app: pomerium-httpbin
    spec:
      containers:
        - image: kennethreitz/httpbin:latest
          imagePullPolicy: IfNotPresent
          name: httpbin
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin
  annotations:
    ingress.pomerium.io/allowed_domains: |
      - webonyx.com
    ingress.pomerium.io/pass_identity_headers: 'true'
spec:
  ingressClassName: pomerium
  rules:
    - host: 'httpbin.localhost.pomerium.io'
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: httpbin
                port:
                  name: http
